### ISSUE TITLE
Update vulnerable nuget package

### ISSUE THREAD

**Issue by MagicAndre1981** [drasticactions/FishyFlip#12]
When opening `FishyFlip.sln` I get a message about nuget package with vulnerabilities and nuget shows `System.IdentityModel.Tokens.Jwt` 7.0.2, so update it to 7.2.0:

![image](https://github.com/drasticactions/FishyFlip/assets/8274816/51f491ab-ab97-4fe7-8fa6-c205ec2e91f9)

**Comment by drasticactions** [comment]
Updated with https://github.com/drasticactions/FishyFlip/commit/41471a3a99cb61a8741ce6e18ad4d64f1501d688
