### ISSUE TITLE
Typo in LabelParameter?

### ISSUE THREAD

**Issue by raymondandreassen** [drasticactions/FishyFlip#139]
I ask because I'm still not comfortable with the terminology surrounding moderation, labels, labelers, etc. 
If I was 100% sure, you would get an PR instead of a question. 
 

In the code below, 
```    /// <param name="labelDid">The label did.</param>```
Shouldn't it be: 
```    /// <param name="labelDid">The labeler did.</param>```
Since its the did of the labeler account and as far as I know, labels don't have a did. 

```
public class LabelParameter
{
    /// <summary>
    /// Initializes a new instance of the <see cref="LabelParameter"/> class.
    /// </summary>
    /// <param name="labelDid">The labeler did.</param>
    /// <param name="parameters">Optional list of parameters for the label.</param>
    internal LabelParameter(ATDid labelDid, List<string>? parameters = null)
    {
        this.LabelDid = labelDid;
        this.Parameters = parameters ?? new List<string>();
    }
```

**Comment by drasticactions** [comment]
Changed with https://github.com/drasticactions/FishyFlip/commit/b1e255fba1ca5b81cba37b97e30c833dc89e54e9
