### ISSUE TITLE
Task: Enable Dependabot on Directory.Packages.props

### ISSUE THREAD

**Issue by drasticactions** [drasticactions/FishyFlip#14]

**Comment by MagicAndre1981** [comment]
I still see a mix of older and newer nugets in the `Directory.Packages.props` file:

```
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
```

**Comment by drasticactions** [comment]
Dependabot, AFAIK, updates the packages in the shipping Nuget (which it did do in the last go around), and that package is referenced in the sample apps only.
