### ISSUE TITLE
Question: Using polymorphism/derived classes

### ISSUE THREAD

**Issue by raymondandreassen** [drasticactions/FishyFlip#140]
I notice atproto uses typediscriminators. My question is simple, are you considering supporting derived classes?  

I am certain you are familiar with it, but just in case you want an update:  
[How to serialize properties of derived classes with System.Text.Json](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism)

The code will then look something like this: 
```
// For serializing and deserializing. 
[JsonPolymorphic(TypeDiscriminatorPropertyName = "$type", 
    UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToBaseType, 
    IgnoreUnrecognizedTypeDiscriminators = true)]
// The classes
[JsonDerivedType(typeof(FacetBase))]
[JsonDerivedType(typeof(FacetTag), typeDiscriminator: "app.bsky.richtext.facet#tag")]
[JsonDerivedType(typeof(FacetLink), typeDiscriminator: "app.bsky.richtext.facet#link")]
[JsonDerivedType(typeof(FacetMention), typeDiscriminator: "app.bsky.richtext.facet#mention")]
```

**Comment by drasticactions** [comment]
https://github.com/drasticactions/FishyFlip/blob/develop/src/FishyFlip/Lexicon/ATObject.g.cs#L9

A quick search of the codebase shows that it already does. The source generator adds the type based on the lexicon value, and that's how the System.Text.Json source generation is derived. 

When I started 3.x, I didn't know it existed until someone in the Bluesky Dev Discord pointed me to it. This solved many problems I had with reading potentially malformed or malicious JSON. 

I'm open to improvements, but everything in the lexicon should already be included.
