### ISSUE TITLE
Implement Equals() and GetHashCode() for pointer types

### ISSUE THREAD

**Issue by UpcraftLP** [drasticactions/FishyFlip#2]
`ATIdentifier` and subclasses, `AtUri`, and any other type that are just typed wrappers for a string-like object should have an `Equals()` and `GetHashCode()` implementation so that they can be used as dictionary keys etc.

**Comment by drasticactions** [comment]
Fixed with https://github.com/drasticactions/FishyFlip/commit/9f2db36e023e9c9bce8aa9a575c9bdcb21f3e5d8
