### ISSUE TITLE
How to identify whether post is reply when streaming?

### ISSUE THREAD

**Issue by vantubbe** [drasticactions/FishyFlip#29]
When streaming via...

private async Task HandleMessageAsync(SubscribeRepoMessage message)

Is there a way to tell whether the message (assuming a Post type) is replying (has parent) to another post?

**Comment by drasticactions** [comment]
There should be, but I think I may not be handling it correctly. I believe the `Reply` object should be populated, but it's not. I am not handling the "app.bsky.feed.threadgate" type for ATRecords in the Firehose.

I'll try and fix that.

**Comment by drasticactions** [comment]
Should be fixed with https://github.com/drasticactions/FishyFlip/commit/59cbff89623a4d8b911ab7730cc8d6024c5ffbd9

Uploaded [https://www.nuget.org/packages/FishyFlip/1.7.31-alpha](1.7.31-alpha). Please try that and let me know if that works for you, thanks!

**Comment by vantubbe** [comment]
Wow. That was insanely fast. My company pays 300k/yr for enterprise support and haven't ever even _responded_ that fast. Thank you very much!
