### ISSUE TITLE
Remove Invite code

### ISSUE THREAD

**Issue by MagicAndre1981** [drasticactions/FishyFlip#45]
Invites are gone, so the code should be removed from the lib.

**Comment by drasticactions** [comment]
While it's not needed to access the primary Bluesky instance, the code is still very much [a part of ATProto](https://github.com/search?q=org%3Abluesky-social%20createInviteCode&type=code) and hasn't been removed. A user could theoretically activate it as part of their instance and implement it.

Unless it's deprecated in ATProto, it stays here.
