### ISSUE TITLE
Breaking Changes for 2.0

### ISSUE THREAD

**Issue by drasticactions** [drasticactions/FishyFlip#59]
I am working on getting FishyFlip 2.0 out the door. I have pushed an alpha [release](https://github.com/drasticactions/FishyFlip/releases/tag/v2.0.0-alpha.45) to nuget and it refactors a bunch of code and adds some new features. The biggest change is how authentication works:

2.0 supports OAuth and Password authentication. App Passwords are being phased out of Bluesky/ATProtocol with OAuth being the replacement. However, with OAuth still being worked on while it's being defined, I didn't want to also break password support, but I also needed to refactor the previous methods for how authentication work to make sure both worked correctly.

For this, I have removed the logic that was used when creating a session with `ATProtocol.Server`. The endpoints are still there, but calling them will not automatically set up a new app password session. Instead, I've hopefully made it easier by moving it to a new method:

https://github.com/drasticactions/FishyFlip/blob/85d0581617b3f77f87385042163121dae6d31a5d/src/FishyFlip/ATProtocol.cs#L172

After creating an `ATProtocol`, calling `AuthenticateWithPasswordAsync` with your identifier and password will let you sign in with your password, and do the same logic as what happened before with the direct calls to the endpoint.

I am working on updating all of the documentation for how this and OAuth works. I believe the current API should be stable at this point, I don't expect to make any other changes.

**Comment by TimBurga** [comment]
can you publish a snippet that demonstrates how to create an oauth session?
