### ISSUE TITLE
Parent missing from GetPostThreadAsync

### ISSUE THREAD

**Issue by NotNite** [drasticactions/FishyFlip#66]
Hi! Working on a Bluesky client with FishyFlip [here](https://github.com/NotNite/ImSky). See title. I need to be able to fetch the parent of a post with

```cs
var result = (await atProto.AtProtocol.Feed.GetPostThreadAsync(post.PostUri)).HandleResult();
var parent = result.Thread.Parent;
```

but `Parent` does not exist on `ThreadView` (see [here](https://github.com/bluesky-social/atproto/blob/09656d6db548d18da88ff580aab70a848613584f/lexicons/app/bsky/feed/defs.json#L101-L104)). This led me down a very annoying logic bug with reply refs :(.

**Comment by drasticactions** [comment]
Yep, it wasn't in the object. Good news is that it's easy to add,

https://github.com/drasticactions/FishyFlip/commit/d07d070364075107473c67244eef32da3d578777

<img width="630" alt="スクリーンショット 2024-10-28 16 36 01" src="https://github.com/user-attachments/assets/a6372a88-3682-4031-ab17-62fb65f8b46e">
