### ISSUE TITLE
Viewer missing from PostView

### ISSUE THREAD

**Issue by NotNite** [drasticactions/FishyFlip#67]
See [here](https://github.com/bluesky-social/atproto/blob/09656d6db548d18da88ff580aab70a848613584f/lexicons/app/bsky/feed/defs.json#L31).

**Comment by drasticactions** [comment]
This should be addressed with https://github.com/drasticactions/FishyFlip/pull/69, note that it seems there are a few more `Viewer` objects also need to be added. This at least does the one you saw.

As you're building a full blown client based off of this library, and these fields are more out of the range of what I usually use this library for myself (Ex. Bot activity and posting), IMO, I would submodule this, add the missing fields as you see them for your app, and PR them back if you like. That would unblock you and not rely on me to make these changes.

Of course you can keep filing issues (Although if you could please post example JSON you're seeing, AT-URIs, etc, that would be nicer than just posting a link to the lexicon), but your at my time for doing it. Thanks!

**Comment by NotNite** [comment]
> IMO, I would submodule this, add the missing fields as you see them for your app, and PR them back if you like. That would unblock you and not rely on me to make these changes.

Yeah, I considered it, but I was trying to avoid submodules as I don't really like working with them + don't want to publish a fork of a package to NuGet. I'll keep it in mind for the future.

> Of course you can keep filing issues (Although if you could please post example JSON you're seeing, AT-URIs, etc, that would be nicer than just posting a link to the lexicon), but your at my time for doing it. Thanks!

I'm fine with waiting if you're okay with more issues 😄, but I can PR them if I end up going down the fork route.
